=== Yahimchik/Epam/task07/target/classes/data.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://training.by/xmlparser/entity/devices"
           xmlns:tns="http://training.by/xmlparser/entity/devices"
           elementFormDefault="qualified">

    <xs:element name="sales">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:subscription_sale" minOccurs="16" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="sale" type="tns:Sale" abstract="true"/>
    <xs:element name="subscription_sale" type="tns:SubSale" substitutionGroup="tns:sale"/>

    <xs:complexType name="Sale" mixed="true">
        <xs:sequence>
            <xs:element name="client" type="tns:Client"/>
            <xs:element name="subscription" type="tns:Subscription"/>
            <xs:element name="specialization" type="tns:Specialization"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>

    <xs:complexType name="SubSale" mixed="true">
        <xs:complexContent>
            <xs:extension base="tns:Sale">
                <xs:sequence>
                    <xs:element name="card_number">
                        <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:pattern value="\b(?:[1-9]|\d{2,})\b"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="user_id">
                        <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:pattern value="\b(?:[1-9]|\d{2,})\b"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="start_date" type="xs:dateTime"/>
                    <xs:element name="end_date" type="xs:dateTime"/>
                    <xs:element name="service_id">
                        <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:pattern value="\b(?:[1-9]|\d{2,})\b"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Client" mixed="true">
        <xs:sequence>
            <xs:element name="id_client" default="client">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="\b(?:[1-9]|\d{2,})\b"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="f_name_client" type="xs:string" default="client"/>
            <xs:element name="s_name_client" type="xs:string" default="client"/>
            <xs:element name="l_name_client" type="xs:string" default="client"/>
            <xs:element name="address_client" type="xs:string" default="client"/>
            <xs:element name="phone_client" type="xs:string" default="client"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Subscription">
        <xs:sequence>
            <xs:element name="id_sub" default="subscription">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="\b(?:[1-9]|\d{2,})\b"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="name_sub" type="xs:string" default="subscription"/>
            <xs:element name="price" default="subscription">
                <xs:simpleType>
                    <xs:restriction base="xs:double">
                        <xs:pattern value="(\d{1,2}|100)$"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="visits" default="subscription">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="^([1-2]?[\d]|3[0-1])$"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="days" default="subscription">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="^([1-2]?[\d]|3[0-2])$"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Specialization">
        <xs:sequence>
            <xs:element name="id_spec" default="specialization">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="\b(?:[1-9]|\d{2,})\b"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="note" type="xs:string" default="specialization"/>
            <xs:element name="service" type="tns:Service"/>
            <xs:element name="employee" type="tns:Employee"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Service">
        <xs:sequence>
            <xs:element name="id_serv" default="service">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="\b(?:[1-9]|\d{2,})\b"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="name_serv" type="xs:string" default="service"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Employee">
        <xs:sequence>
            <xs:element name="id_employee" default="employee">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="\b(?:[1-9]|\d{2,})\b"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="f_name_employee" type="xs:string" default="employee"/>
            <xs:element name="s_name_employee" type="xs:string" default="employee"/>
            <xs:element name="l_name_employee" type="xs:string" default="employee"/>
            <xs:element name="address_employee" type="xs:string" default="employee"/>
            <xs:element name="phone_employee" type="xs:string" default="employee"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Yahimchik/Epam/task07/src/main/resources/data.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://http://by.yahimovich/task07/src/main/resources"
       xsi:schemaLocation="http://http://by.yahimovich/task07/src/main/resources data.xsd
">
    <subscription_sale id="1">
        <card_number>1</card_number>
        <user_id>1</user_id>
        <start_date>12.02.2022 11:00</start_date>
        <end_date>12.03.2022 11:00</end_date>
        <service_id>2</service_id>
        <client>
            <id_client>1</id_client>
            <f_name_client>Yahimovich</f_name_client>
            <s_name_client>Egor</s_name_client>
            <l_name_client>Aleksandrovich</l_name_client>
            <address_client>Vileyka</address_client>
            <phone_client>+375333139380</phone_client>
        </client>
        <subscription>
            <id_sub>1</id_sub>
            <name_sub>Premium</name_sub>
            <price>50</price>
            <visits>15</visits>
            <days>30</days>
        </subscription>
        <specialization>
            <id_spec>1</id_spec>
            <note>Master of Sport</note>
            <service>
                <id_serv>2</id_serv>
                <name_serv>powerlifting</name_serv>
            </service>
            <employee>
                <id_employee>2</id_employee>
                <f_name_employee>Scridlevskiy</f_name_employee>
                <s_name_employee>Aleksey</s_name_employee>
                <l_name_employee>Aleksandrovich</l_name_employee>
                <address_employee>Slyck</address_employee>
                <phone_employee>+375294859261</phone_employee>
            </employee>
        </specialization>
    </subscription_sale>
    <subscription_sale id="2">
        <card_number>2</card_number>
        <user_id>1</user_id>
        <start_date>12.02.2022 11:00</start_date>
        <end_date>12.03.2022 11:00</end_date>
        <service_id>2</service_id>
        <client>
            <id_client>1</id_client>
            <f_name_client>Pavlovich</f_name_client>
            <s_name_client>Egor</s_name_client>
            <l_name_client>Aleksandrovich</l_name_client>
            <address_client>Vileyka</address_client>
            <phone_client>+375333139380</phone_client>
        </client>
        <subscription>
            <id_sub>1</id_sub>
            <name_sub>Premium</name_sub>
            <price>50</price>
            <visits>15</visits>
            <days>30</days>
        </subscription>
        <specialization>
            <id_spec>1</id_spec>
            <note>Master of Sport</note>
            <service>
                <id_serv>2</id_serv>
                <name_serv>powerlifting</name_serv>
            </service>
            <employee>
                <id_employee>2</id_employee>
                <f_name_employee>Scridlevskiy</f_name_employee>
                <s_name_employee>Aleksey</s_name_employee>
                <l_name_employee>Aleksandrovich</l_name_employee>
                <address_employee>Slyck</address_employee>
                <phone_employee>+375294859261</phone_employee>
            </employee>
        </specialization>
    </subscription_sale>
    <subscription_sale id="3">
        <card_number>3</card_number>
        <user_id>1</user_id>
        <start_date>12.02.2022 11:00</start_date>
        <end_date>12.03.2022 11:00</end_date>
        <service_id>2</service_id>
        <client>
            <id_client>1</id_client>
            <f_name_client>Skridlevskiy</f_name_client>
            <s_name_client>Egor</s_name_client>
            <l_name_client>Aleksandrovich</l_name_client>
            <address_client>Vileyka</address_client>
            <phone_client>+375333139380</phone_client>
        </client>
        <subscription>
            <id_sub>1</id_sub>
            <name_sub>Premium</name_sub>
            <price>50</price>
            <visits>15</visits>
            <days>30</days>
        </subscription>
        <specialization>
            <id_spec>1</id_spec>
            <note>Master of Sport</note>
            <service>
                <id_serv>2</id_serv>
                <name_serv>powerlifting</name_serv>
            </service>
            <employee>
                <id_employee>2</id_employee>
                <f_name_employee>Scridlevskiy</f_name_employee>
                <s_name_employee>Aleksey</s_name_employee>
                <l_name_employee>Aleksandrovich</l_name_employee>
                <address_employee>Slyck</address_employee>
                <phone_employee>+375294859261</phone_employee>
            </employee>
        </specialization>
    </subscription_sale>
    <subscription_sale id="4">
        <card_number>4</card_number>
        <user_id>1</user_id>
        <start_date>11.02.2022 11:00</start_date>
        <end_date>11.03.2022 11:00</end_date>
        <service_id>2</service_id>
        <client>
            <id_client>1</id_client>
            <f_name_client>Pavlovich</f_name_client>
            <s_name_client>Egor</s_name_client>
            <l_name_client>Aleksandrovich</l_name_client>
            <address_client>Vileyka</address_client>
            <phone_client>+375333139380</phone_client>
        </client>
        <subscription>
            <id_sub>1</id_sub>
            <name_sub>Premium</name_sub>
            <price>50</price>
            <visits>15</visits>
            <days>30</days>
        </subscription>
        <specialization>
            <id_spec>1</id_spec>
            <note>Master of Sport</note>
            <service>
                <id_serv>2</id_serv>
                <name_serv>powerlifting</name_serv>
            </service>
            <employee>
                <id_employee>2</id_employee>
                <f_name_employee>Scridlevskiy</f_name_employee>
                <s_name_employee>Aleksey</s_name_employee>
                <l_name_employee>Aleksandrovich</l_name_employee>
                <address_employee>Slyck</address_employee>
                <phone_employee>+375294859261</phone_employee>
            </employee>
        </specialization>
    </subscription_sale>
    <subscription_sale id="5">
        <card_number>5</card_number>
        <user_id>1</user_id>
        <start_date>12.02.2022 11:00</start_date>
        <end_date>12.03.2022 11:00</end_date>
        <service_id>2</service_id>
        <client>
            <id_client>1</id_client>
            <f_name_client>Pavlovich</f_name_client>
            <s_name_client>Egor</s_name_client>
            <l_name_client>Aleksandrovich</l_name_client>
            <address_client>Vileyka</address_client>
            <phone_client>+375333139380</phone_client>
        </client>
        <subscription>
            <id_sub>1</id_sub>
            <name_sub>Premium</name_sub>
            <price>50</price>
            <visits>15</visits>
            <days>30</days>
        </subscription>
        <specialization>
            <id_spec>1</id_spec>
            <note>Master of Sport</note>
            <service>
                <id_serv>2</id_serv>
                <name_serv>powerlifting</name_serv>
            </service>
            <employee>
                <id_employee>2</id_employee>
                <f_name_employee>Scridlevskiy</f_name_employee>
                <s_name_employee>Aleksey</s_name_employee>
                <l_name_employee>Aleksandrovich</l_name_employee>
                <address_employee>Slyck</address_employee>
                <phone_employee>+375294859261</phone_employee>
            </employee>
        </specialization>
    </subscription_sale>
    <subscription_sale id="6">
        <card_number>6</card_number>
        <user_id>1</user_id>
        <start_date>12.02.2022 11:00</start_date>
        <end_date>12.03.2022 11:00</end_date>
        <service_id>2</service_id>
        <client>
            <id_client>1</id_client>
            <f_name_client>Pavlovich</f_name_client>
            <s_name_client>Egor</s_name_client>
            <l_name_client>Aleksandrovich</l_name_client>
            <address_client>Vileyka</address_client>
            <phone_client>+375333139380</phone_client>
        </client>
        <subscription>
            <id_sub>1</id_sub>
            <name_sub>Premium</name_sub>
            <price>50</price>
            <visits>15</visits>
            <days>30</days>
        </subscription>
        <specialization>
            <id_spec>1</id_spec>
            <note>Master of Sport</note>
            <service>
                <id_serv>2</id_serv>
                <name_serv>running</name_serv>
            </service>
            <employee>
                <id_employee>2</id_employee>
                <f_name_employee>Scridlevskiy</f_name_employee>
                <s_name_employee>Aleksey</s_name_employee>
                <l_name_employee>Aleksandrovich</l_name_employee>
                <address_employee>Slyck</address_employee>
                <phone_employee>+375294859261</phone_employee>
            </employee>
        </specialization>
    </subscription_sale>
    <subscription_sale id="7">
        <card_number>7</card_number>
        <user_id>1</user_id>
        <start_date>12.02.2022 11:00</start_date>
        <end_date>12.03.2022 11:00</end_date>
        <service_id>2</service_id>
        <client>
            <id_client>1</id_client>
            <f_name_client>Pavlovich</f_name_client>
            <s_name_client>Egor</s_name_client>
            <l_name_client>Aleksandrovich</l_name_client>
            <address_client>Vileyka</address_client>
            <phone_client>+375333139380</phone_client>
        </client>
        <subscription>
            <id_sub>1</id_sub>
            <name_sub>Premium</name_sub>
            <price>50</price>
            <visits>15</visits>
            <days>30</days>
        </subscription>
        <specialization>
            <id_spec>1</id_spec>
            <note>Master of Sport</note>
            <service>
                <id_serv>2</id_serv>
